### PR TITLE
#Add greetings bot

### LINKED ISSUE #1: Add Github Greetings Bot
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24 Ext)

### PR DESCRIPTION
**Pull request by KiranBaliga**
This is a PR that addresses the addition of a simple github greetings bot that display messages in the form of comments to the new users who raise a PR or an issue. Please add level1 and gssoc24-ext labels to the PR. Thank you. 

closes #1

### CODE REVIEW

**Comment by KiranBaliga** [comment]
Please add level1 and gssoc24-ext, hacktoberfest-accepted labels to the PR. Thank you!

**Review by SwanandD121 — COMMENTED** [review]
If you can make this more custom like putting "FindFeather team" instead of "Our team" or anything similar, it would be good.

**Comment by KiranBaliga** [comment]
@SwanandD121 Requested changes has been pushed via new commit. Please review.

**Review by SwanandD121 — APPROVED** [review]
Good Work

**Pull request merged**
