### PR TITLE
[FIX] login page logo full not visible #3

### PR DESCRIPTION
**Pull request by Vinayyy19**
### Title: Fix Logo Cutoff on Sign-Up Page

**Description**  
The logo on the sign-up page is cut off at the bottom, impacting the overall user interface.

**Related Issue**  
Fixes [#3](https://github.com/SwanandD121/FeatherPerfect_fe/issues/3).

**Changes Made**  
- **Updated UI**: Adjusted the layout of the authentication page to enhance user experience.
- **Improved Heading Styles**: Reduced the font size and spacing of the `<h1>` element for better alignment and to prevent excessive space usage.

**Testing Instructions**  
Navigate to the sign-up page to verify that the logo is now fully visible.

### CODE REVIEW

**Review by SwanandD121 — COMMENTED** [review]
Line 19 and line 20 should be properly indented.

**Comment by SwanandD121** [comment]
Now line 21 is also badly indented, line 19, 20 and 21 should be nested in the div.
We take care of code readability, so please do the needful.

**Comment by Vinayyy19** [comment]
image
i think it was looking good

**Comment by SwanandD121** [comment]
> image i think it was looking good

just press 'tab' before line 19, 20 and 21 starts, this will indent them correctly and the code readability will improve.

**Comment by Vinayyy19** [comment]
@SwanandD121 check now

**Review by SwanandD121 — APPROVED** [review]
This was what I wanted

**Pull request merged**
