### PR TITLE
toasts  added

### PR DESCRIPTION
**Pull request by ChandraST12**
issue #16 Added toast notifications to dummy login and signup handlers since the functions were not available.

### CODE REVIEW

**Comment by ChandraST12** [comment]
@SwanandD121, I kindly request you to merge this PR as soon as possible, as the contribution needs to be counted toward GSSoC-extd. Thank you!

**Review by SwanandD121 — CHANGES_REQUESTED** [review]
remove the .vscode folder and commit again, I cannot merge the .vscode file

**Comment by SwanandD121** [comment]
resolve conflicts

**Comment by ChandraST12** [comment]
> resolved conflicts

**Pull request merged**
